[versions]
ksp = "1.9.22-1.0.16"
kotlin = "1.9.22"
application = "8.2.1"
firebase-crashlytics = "18.6.0"
firebase-analytics = "21.5.0"
firebase-auth = "22.3.0"
gradle-build = "8.2.1"
google-services = "4.4.0"
crashlytics-gradle = "2.9.9"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso = "3.5.1"
navigation = "2.7.6"
core = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
retrofit = "2.9.0"
timber = "5.0.1"
swiperefresh = "1.2.0-alpha01"
coil = "2.5.0"
paging = "3.2.1"
lifecycle = "2.6.2"
coroutines = "1.7.3"
moshi = "1.15.0"
datastore = "1.0.0"
hilt = "2.50"

[libraries]
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase-auth" }

build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle-build" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services"}
crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "application" }